#已在nacos发布
#dubbo:
#  registry:
#    address: nacos://ip:8848
#  cloud:
#    subscribed-services:
#  protocol:
#    id: waterflood-consumer
#    name: dubbo
#    port: -1
#  consumer:
#    timeout: 5000
#    check: false
#server:
#  port: 9004
#spring:
#  application:
#    name: group06-api-core
#  redis:
#    database: 0
#    host: ip        # Redis服务器地址
#    port: 6379              # Redis服务器连接端口
#    password:               # Redis服务器连接密码（默认为空）
#    timeout: 2000
#    lettuce:
#      pool:
#        max-active: 200       # 连接池最大连接数（使用负值表示没有限制）
#        max-idle: 10          # 连接池中的最大空闲连接
#        max-wait: -1          # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        min-idle: 0           # 连接池中的最小空闲连接
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    name: product
#    password: 'password'
#    url: jdbc:mysql://
#    username: 'root'
#knife4j:
#  enable: false
#  openapi:
#    title: 注水井综合评价系统API文档
#    description: 注水井综合评价系统
#    # aaa"
#    email: xiaoymin@foxmail.com
#    concat: CUPK
#    url: https://docs.xiaominfo.com
#    version: v4.0
#    license: Apache 2.0
#    license-url: https://stackoverflow.com/
#    terms-of-service-url: https://stackoverflow.com/
#    group:
#      test1:
#        group-name: 分组名称
#        api-rule: package
#        api-rule-resources:
#          - club.cupk.waterflood.controller