version: '3'
services:
  waterflood-consumer-9004:
    image: openjdk:8-alpine
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./target:/tmp
    ports:
      - 9004:9004
    command: java -jar /tmp/waterflood-consumer-9004-0.0.1-SNAPSHOT.jar
