#已在nacos配置
#server:
#  port: 9010
#spring:
#  application:
#    name: gateway
#  cloud:
#    nacos:
#      discovery:
#        namespace: public
#        password: nacos
#        server-addr: ip:8848
#        username: nacos
#    gateway:
#      # 允许跨域请求配置
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            # 允许任何域名使用
#            allowedOrigins: "*"
#            # 允许任何头
#            allowedHeaders: "*"
#            # 允许任何方法(post、get等)
#            allowedMethods: "*"
#            # sessionid 多次访问一致
#            allowCredentials: true
#        # 允许来自所有域名(allowedOrigins)的所有请求方式(allowedMethods)发出CORS请求
#        add-to-simple-url-handler-mapping: true   # 允许来自所有域名(allowedOrigins)的所有请求方式(allowedMethods)发出CORS请求
#      routes:
#        - id: auth-service
#          uri: http://localhost:9011
#          predicates:
#            - Path=/auth/**
#          filters:
#            - StripPrefix=1
#        - id: api-core
#          uri: http://localhost:9012
#          predicates:
#            - Path=/api/**
#          filters:
#            - StripPrefix=1
#        - id: api-system
#          uri: http://localhost:9013
#          predicates:
#            - Path=/system/**
#          filters:
#            - StripPrefix=1